name: Quality assurance

on: [push]

env:
  GO_VERSION: '1.25.7'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Check code style with golangci-lint
      uses: golangci/golangci-lint-action@v9
    - name: Check code style with revive
      uses: docker://morphy/revive-action:v2
      with:
        exclude: "./examples/..."
        config: revive.toml
        path: "./..."

    - name: Check package build
      run: make build

    - name: Test
      run: make test